geocoder:
  build: .
  ports:
    - "31010:31010"
  environment:
    ELASTICSEARCH_HOST: elasticsearch
    # NOTE: Official ES image has a ELASTICSEARCH_PORT envvar,
    # but it actually host/port, so it MUST be overridden here.
    ELASTICSEARCH_PORT: 9300
    GRASSHOPPER_PARSER_HOST: parser
    GRASSHOPPER_PARSER_PORT: 5000

parser:
  build: ../grasshopper-parser
  ports:
    - "5000:5000"

loader:
  build: ../grasshopper-loader
  #command: ./grasshopper-loader.js -d test/data/new_york.json

# Must be named "elasticsearch" to create expected ELASTICSEARCH_* envvars
elasticsearch:
  image: elasticsearch:2.2.0

ui:
  build: ../grasshopper-ui
  ports:
    - "80:80"
