# dev compose
# extend from docker-compose-common.yml
geocoder:
  extends:
    file: docker-compose-common.yml
    service: geocoder
  links:
    - lines
    - points
    - parser

lines:
  extends:
    file: docker-compose-common.yml
    service: lines
  links: 
    - elasticsearch

points:
  extends:
    file: docker-compose-common.yml
    service: points
  links: 
    - elasticsearch

parser:
  extends:
    file: docker-compose-common.yml
    service: parser

loader:
  extends:
    file: docker-compose-common.yml
    service: loader
  links:
    - elasticsearch

# add port to make it viewable
elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  ports:
    - "9200:9200"

ui:
  extends:
    file: docker-compose-common.yml
    service: ui
  links:
    - geocoder
    - lines
    - points
    - parser
  volumes:
    - .:/grasshopper-ui/dist
